[config]
version_check = false

[config.wallpaper]
set = false

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/matugen.css"
post_hook = "pkill -SIGUSR2 waybar 2>/dev/null || true"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/matugen.css"
post_hook = "command -v swaync-client >/dev/null 2>&1 && swaync-client -rs || true"

