[tools]
bun = "latest"
claude-code = "latest"
codex = "latest"
node = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:mmx-cli" = "latest"
opencode = "latest"
pdm = "latest"
typst = "latest"
uv = "latest"
viteplus = "latest"
